### ISSUE TITLE
FetchError: request to http://localhost/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by carloslenz** [miragejs/graphql#33]
I'm trying to run a sample from README.md.

Node version: v14.16.0

- package.json
```
{
  "devDependencies": {
    "@miragejs/graphql": "^0.1.11",
    "graphql-request": "^3.4.0",
    "miragejs": "^0.1.41"
  }
}
```

- test.js
```
const { createServer } = require("miragejs")
const { createGraphQLHandler } = require("@miragejs/graphql")
const { request } = require("graphql-request")

const graphQLSchema = `
input PersonInput {
  firstName: String
  lastName: String
}

type Mutation {
  createPerson(input: PersonInput!): Person
  updatePerson(id: ID!, input: PersonInput!): Person

  deletePerson(id: ID!): Boolean
}

type Person {
  id: ID!
  firstName: String!
  lastName: String!
}

type Query {
  allPeople: [Person]
  person(id: ID!): Person

  people(firstName: String, lastName: String, sortBy: String): [Person]
}
`

const URL = "http://localhost/graphql"

const server = createServer({
  routes() {
    const graphQLHandler = createGraphQLHandler(graphQLSchema, this.schema);

    this.post(URL, graphQLHandler)
  }
})

server.create("person", { firstName: "Mikael", lastName: "Åkerfeldt" })

const personQuery = `
  query Person($id: id) {
    person(id: $id) {
      id
      firstName
      lastName
    }
  }
`

request(URL, personQuery, { id: "1" }).then(
  console.log,
  console.error,
).finally(
  () => console.log('DONE')
)
```

- Execution
```
$ node test.js 
FetchError: request to http://localhost/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:80
    at ClientRequest.<anonymous> (/home/cel/projects/my/mirage/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
DONE
```

**Comment by jneurock** [comment]
Hi. The error you're seeing is due to Mirage itself. It's not intercepting the network request. I believe this is due to the environment (Node). I'm not sure about the specifics of this (it has to do with Mirage's dependence on Pretender) and I'm not sure if there's an easy way to make this work.

Alternatively, you could try the example code in a browser or use a testing framework like Jest.

**Comment by carloslenz** [comment]
Not working in jest either.

- package.json
```
{
  "scripts": {
    "test": "jest test.js"
  },
  "devDependencies": {
    "@miragejs/graphql": "^0.1.11",
    "graphql-request": "^3.4.0",
    "jest": "^26.6.3",
    "miragejs": "^0.1.41"
  }
}
```

- test.js
```
const { createServer } = require("miragejs")
const { createGraphQLHandler } = require("@miragejs/graphql")
const { request } = require("graphql-request")

const graphQLSchema = `
input PersonInput {
  firstName: String
  lastName: String
}

type Mutation {
  createPerson(input: PersonInput!): Person
  updatePerson(id: ID!, input: PersonInput!): Person

  deletePerson(id: ID!): Boolean
}

type Person {
  id: ID!
  firstName: String!
  lastName: String!
}

type Query {
  allPeople: [Person]
  person(id: ID!): Person

  people(firstName: String, lastName: String, sortBy: String): [Person]
}
`

const URL = "http://localhost/graphql"

describe('mirage', () => {
  beforeAll(() => {
    const server = createServer({
      routes() {
        const graphQLHandler = createGraphQLHandler(graphQLSchema, this.schema);
    
        this.post(URL, graphQLHandler)
      }
    })
    
    server.create("person", { firstName: "Mikael", lastName: "Åkerfeldt" })
  })

  it('request', () => {
    const personQuery = `
      query Person($id: id) {
        person(id: $id) {
          id
          firstName
          lastName
        }
      }
    `
    return request(URL, personQuery, { id: "1" }).then(
      console.log,
      console.error,
    ).finally(
      () => console.log('DONE')
    )
  })
})
```

- Execution
```
$ npm run test

> test
> jest test.js

 PASS  ./test.js
  mirage
    ✓ request (25 ms)

  console.error
    FetchError {
      message: 'request to http://localhost/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:80',
      type: 'system',
      errno: 'ECONNREFUSED',
      code: 'ECONNREFUSED'
    }

  console.log
    DONE

      at test.js:61:21

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.852 s
Ran all test suites matching /test.js/i.
```

**Comment by jneurock** [comment]
I did a little checking and in this lib we use `graphql-request` 2.x and the tests fail in the same way yours do if I bump the version to 3.4.x.

**Comment by carloslenz** [comment]
Downgrading is not an option for me. I was planning to use miragejs/graphql to test a real project and using an unsupported version of graphql-request (2.0.0 is the only 2.x version) is risky.

**Comment by jneurock** [comment]
Yeah, totally hear you on that. This issue needs some research to understand the changes between `graphql-request` 2.x vs. 3.x but I'm pretty confident it will need to be raised in the Pretender project or maybe Mirage where code changes would be needed. This library doesn't contain any code to actually deal with network requests.

**Comment by jneurock** [comment]
For version `0.2.0` of this library, I updated `graphql-request` to the latest version. Indeed, I needed to change the integration tests to run in a browser instead of Node. This is exactly because Mirage/Pretender only work in browsers. Closing this issue here since there's nothing I can do to make it work from this library.
